name: Build YeeeesMOTD
on:
  - push
jobs:
  build:
    strategy:
      matrix:
        java:
          - 21
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: YeeeesMOTD
          path: build/libs/*.jar